[tool.black]
line-length = 100
include = '\.pyi?$'
extend-exclude = '\.html$'
'''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/foo.py  # exclude a file named foo.py in the root of the project (in addition to the defaults)
'''
skip-string-normalization = true