# Generated by Django 5.1.3 on 2024-11-22 02:58

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', martor.models.MartorField(verbose_name='Contenido')),
                ('excerpt', martor.models.MartorField(verbose_name='Extracto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Estado')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Imágen Destacada')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
