# Generated by Django 5.1.3 on 2024-11-24 13:58

import taggit.managers
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('web', '0003_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('overview', tinymce.models.HTMLField(verbose_name='Descripción General')),
                ('year', models.DateField(blank=True, null=True, verbose_name='Año')),
                ('repo', models.URLField(blank=True, help_text='URL de GitHub, GitLab, BitBucket, etc.', null=True, verbose_name='URL del Repositorio')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL del Proyecto')),
                ('intro', tinymce.models.HTMLField(verbose_name='Introducción')),
                ('goals', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Objetivos')),
                ('challenges', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Desafíos y Dificultades')),
                ('solutions', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Soluciones Implementadas')),
                ('impact', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Impactos del Proyecto')),
                ('conclusion', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Conclusión')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Selecciona uno o más tags', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
