# Generated by Django 5.1.3 on 2024-12-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_post_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
