# Generated by Django 5.1.3 on 2024-12-01 12:48

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_tagpost_taggedpost_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech',
            field=taggit.managers.TaggableManager(help_text='Selecciona una o más tecnologías', through='web.TaggedProject', to='web.TagProject', verbose_name='Tecnologías'),
        ),
    ]
