# Generated by Django 5.1.3 on 2024-12-01 20:09

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_project_tech'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=filer.fields.image.FilerImageField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Imágen Destacada'),
            preserve_default=False,
        ),
    ]
