# Generated by Django 5.1.3 on 2024-12-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_project_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_image',
        ),
    ]
