# Generated by Django 5.1.3 on 2024-12-02 19:33

from django.db import migrations, models
from django.utils.text import slugify
from web.models import Project


def populate_project_slug_field(apps, schema_editor):
    for project in Project.objects.all():
        project.slug = slugify(project.name)
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.RunPython(
            populate_project_slug_field,
        ),
    ]
