# Generated by Django 5.1.3 on 2024-12-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
