# Generated by Django 5.1.3 on 2024-12-04 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_image', to='web.project', verbose_name='Proyecto'),
        ),
    ]
