# Generated by Django 5.1.3 on 2024-12-11 00:42

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_projectimage_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', martor.models.MartorField(verbose_name='Contenido')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
        ),
    ]
