# Generated by Django 5.1.3 on 2024-12-11 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Sobre mi', 'verbose_name_plural': 'Sobre mi'},
        ),
    ]
