# Generated by Django 5.1.3 on 2025-02-20 03:07

import martor.models
import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_about_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='content_en',
            field=martor.models.MartorField(null=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='about',
            name='content_es',
            field=martor.models.MartorField(null=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Desafíos y Dificultades'),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges_es',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Desafíos y Dificultades'),
        ),
        migrations.AddField(
            model_name='project',
            name='conclusion_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Conclusión'),
        ),
        migrations.AddField(
            model_name='project',
            name='conclusion_es',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Conclusión'),
        ),
        migrations.AddField(
            model_name='project',
            name='goals_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Objetivos'),
        ),
        migrations.AddField(
            model_name='project',
            name='goals_es',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Objetivos'),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Impactos del Proyecto'),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_es',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Impactos del Proyecto'),
        ),
        migrations.AddField(
            model_name='project',
            name='intro_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Introducción'),
        ),
        migrations.AddField(
            model_name='project',
            name='intro_es',
            field=tinymce.models.HTMLField(null=True, verbose_name='Introducción'),
        ),
        migrations.AddField(
            model_name='project',
            name='overview_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Descripción General'),
        ),
        migrations.AddField(
            model_name='project',
            name='overview_es',
            field=tinymce.models.HTMLField(null=True, verbose_name='Descripción General'),
        ),
        migrations.AddField(
            model_name='project',
            name='solutions_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Soluciones Implementadas'),
        ),
        migrations.AddField(
            model_name='project',
            name='solutions_es',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Soluciones Implementadas'),
        ),
    ]
